# Path to oh-my-zsh installation.
export ZSH=$HOME/.oh-my-zsh
export WORKON_HOME=$HOME/.virtualenvs

ZSH_THEME="daveverwer"

# Powertline options
POWERLINE_DETECT_SSH="true"
POWERLINE_GIT_CLEAN="✔"
POWERLINE_GIT_DIRTY="✘"
POWERLINE_GIT_ADDED="%F{green}✚%F{black}"
POWERLINE_GIT_MODIFIED="%F{blue}✹%F{black}"
POWERLINE_GIT_DELETED="%F{red}✖%F{black}"
POWERLINE_GIT_UNTRACKED="%F{yellow}✭%F{black}"
POWERLINE_GIT_RENAMED="➜"
POWERLINE_GIT_UNMERGED="═"
POWERLINE_HIDE_HOST_NAME="true"
POWERLINE_RIGHT_A="exit-status"

# Uncomment the following line to enable command auto-correction.
ENABLE_CORRECTION="true"

# oh-my-zsh plugins
plugins=(git django github virtualenv virtualenvwrapper vundle systemd
         httpie pip cp colorize)

# User configuration
export PATH=$HOME/bin:/usr/local/bin:$PATH

source $ZSH/oh-my-zsh.sh

for config ($HOME/.dotfiles/zsh/zsh.d/*.zsh) source $config

