# Path to oh-my-zsh installation.
export ZSH=$HOME/.oh-my-zsh
export WORKON_HOME=$HOME/.virtualenvs
export MAKEFLAGS=-j16

POWERLEVEL9K_MODE='nerdfont-complete'

ZSH_THEME="powerlevel9k/powerlevel9k"

# Powertline options
POWERLINE_DETECT_SSH="true"
POWERLINE_GIT_CLEAN="✔"
POWERLINE_GIT_DIRTY="✘"
POWERLINE_GIT_ADDED="%F{green}✚%F{black}"
POWERLINE_GIT_MODIFIED="%F{blue}✹%F{black}"
POWERLINE_GIT_DELETED="%F{red}✖%F{black}"
POWERLINE_GIT_UNTRACKED="%F{yellow}✭%F{black}"
POWERLINE_GIT_RENAMED="➜"
POWERLINE_GIT_UNMERGED="═"
POWERLINE_HIDE_HOST_NAME="true"
POWERLINE_RIGHT_A="exit-status"

# Uncomment the following line to enable command auto-correction.
ENABLE_CORRECTION="true"

# oh-my-zsh plugins
plugins=(git django github virtualenv virtualenvwrapper vundle systemd
         httpie pip cp colorize)

# User configuration
export PATH=$HOME/bin:/usr/local/bin:$PATH

export PATH=$HOME/go/bin:$PATH

source $ZSH/oh-my-zsh.sh

for config ($HOME/.dotfiles/zsh/zsh.d/*.zsh) source $config

xset s off -dpms

command -v vg >/dev/null 2>&1 && eval "$(vg eval --shell zsh)"

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
source /usr/share/zsh-theme-powerlevel9k/powerlevel9k.zsh-theme
export PATH=/home/peer/.local/bin/:$PATH

# Base16 Shell
BASE16_SHELL="$HOME/.config/base16-shell/"
[ -n "$PS1" ] && \
    [ -s "$BASE16_SHELL/profile_helper.sh" ] && \
        eval "$("$BASE16_SHELL/profile_helper.sh")"

